### ISSUE TITLE
Include redux-thunk by default

### ISSUE THREAD

**Issue by zsherman** [coryhouse/react-slingshot#121]
Would be nice to have an example of this and the middleware all wired up.

**Comment by coryhouse** [comment]
Considering it, but Redux thunk is easy to wire up and one of 3 popular options. Not sure having an opinion on this is worth it.

**Comment by offsky** [comment]
Im curious. Can you please let us know the other 2 popular options?  Ive been happy with thunk, but Id like to know if there is something better.

Here is how to add redux-thunk. If you don't want to include it by default in this project, maybe this setup could be added to the FAQ or as a separate option for those people who want it.  Or maybe this issue left open is enough for people to find.  

Thanks for making react-slingshot! It saved me a bunch of time bootstrapping my new project.

configureStore.prod.js
```
import {createStore} from 'redux';
import thunk from 'redux-thunk';
import rootReducer from '../reducers';

export default function configureStore(initialState) {
  return createStore(rootReducer, initialState, applyMiddleware(thunk));
}
```

configureStore.dev.js
```
import {createStore, compose, applyMiddleware} from 'redux';
import thunk from 'redux-thunk';
import rootReducer from '../reducers';

export default function configureStore(initialState) {
  const store = createStore(rootReducer, initialState, compose(
        applyMiddleware(thunk),
        window.devToolsExtension ? window.devToolsExtension() : f => f
    )
  );
...
```

Then in an action that wants to use thunk
```
export function myAsyncAction(foo) {
	return function (dispatch, getState) {
		setTimeout(function() {
			dispatch({type: types.MY_ACTION, foo});
		},5000);
	};
}


```

**Comment by coryhouse** [comment]
Given all the options, I'm not sure having an opinion makes sense, but I'm open to accepting a pull request using Redux thunk.

From the [Redux docs](http://redux.js.org/docs/advanced/AsyncActions.html):

Thunk middleware isn’t the only way to orchestrate asynchronous actions in Redux:

You can use redux-promise or redux-promise-middleware to dispatch Promises instead of functions.
You can use redux-observable to dispatch Observables.
You can use the redux-saga middleware to build more complex asynchronous actions.
You can even write a custom middleware to describe calls to your API, like the real world example does.
It is up to you to try a few options, choose a convention you like, and follow it, whether with, or without the middleware.

**Comment by kwelch** [comment]
I personally am fond of the redux-promise library and along with the flux standard action. I have been leveraging redux-actions for consistent action objects. The chaining in promises are really nice and allow for a good distributed domain driven action architecture. 

That being said I think that this is a gray area that depends on the app and architecture in place both in the app and enterprise.

**Comment by coryhouse** [comment]
So @kwelch, do you vote on leaving this out?

**Comment by kwelch** [comment]
I do believe API is useful in almost any app, so I would not overly opposed to redux-thunk, given that it is a good starting point for developers new to the ecosystem. I also think it would not add the same level of complexity that promise/saga/observables will since alone have a learning curve outside of the redux ecosystem. 

Thunks are good even with those other middlewares, particularly in the case of failing out quickly before calling the api (ie. fetch if not already fetched)

**Comment by abekenza** [comment]
Could you please provide an example of getting data from the react-slingshot REST API using redux-thunk?

**Comment by raythree** [comment]
@abekenza redux-thunk gives an example on [this page](https://github.com/gaearon/redux-thunk). You end up writing a lot of boilerplate like:

```javascript
function getDataAsync() {
  return ({dispatch}) => {
    dispatch({type: GET_DATA_PENDING});
    getData()
    .then(data => {
       dispatch({type: GET_DATA, data});
    })
    .catch(err => {
      dispatch({type: GET_DATA_ERROR, error: err});    
    })
  };
}
```
There are other middlewares that automatically handle the promise and dispatch the pending, success and error actions for you so you can just use a regular action creator:
```javascript
function getData() {
  return {type: GET_DATA, payload: getData()};
}
```
and in reducer act on GET_DATA_REQUEST (pending), GET_DATA (success), and GET_DATA_ERROR.

**Comment by tutuca** [comment]
@raythree commented 3 days ago:
> There are other middlewares that automatically handle the promise and dispatch the pending, success and error actions for you.

May you list which one you prefer?

**Comment by raythree** [comment]
@tutuca There is [Redux promise](https://github.com/acdlite/redux-promise) which I've looked at but not yet tried. I've been using [this](https://github.com/raythree/react-slingshot/blob/master/src/middleware/promiseResolver.js) which is a modified version from [Stephen Grider](https://github.com/StephenGrider) but not yet in NPM. I've been very happy with it. And [this](https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/redux/middleware/clientMiddleware.js) also looks good...I'd use any of these.

**Comment by raythree** [comment]
@tutuca I just published [this](https://www.npmjs.com/package/redux-promise-resolver) which is what I've been using. It is very similar to [redux-promise-thunk](https://www.npmjs.com/package/redux-promise-thunk) except that it does not require redux-thunk, and also includes a BYPASS mechanism that I found useful.

**Comment by kwelch** [comment]
Redux thunk has been added to the project. Is there any other updates that should be added to prior to closing this issue?
