### ISSUE TITLE
Organize directories by domain

### ISSUE THREAD

**Issue by nicolas-leydet** [coryhouse/react-slingshot#146]
I always prefered organising my source files by concern instead of by nature (component/action/reducer/...).
I think it is a good practice you can appreciate the benefits when your project grows.
Do you think it would be a good addition to react-slingshot ?

Here's a post that will explain what I am talking about : 
http://marmelab.com/blog/2015/12/17/react-directory-structure.html

**Comment by coryhouse** [comment]
That's an excellent post that I happened to also read over the weekend. I also enjoy doing so on larger apps. However, there are some notable downsides:

1. For someone learning, files organized by type may be easier to understand.
2. Some files may be reused for multiple domains (also known as concern/feature/nature). Organizing by domain makes it unclear where to place such files.
3. Will people understand the need to create a new folder for each new domain?
4. Nearly all React example apps I've seen organize by file type rather than domain.
5. What constitutes a domain worthy of a new folder? A page? A feature? Sometimes this is hard to decide.

The comments in the article highlight some of these concerns.

I tend to organize by file type on small projects and shift to a domain-based structure when complexity justifies the extra work.

That said, I'm open to considering a pull request that implements domain based organization.

**Comment by j5v** [comment]
Seconded, for large projects. I supplied the same link, in a 'code review' of my react-slingshot–based project.

I share your 5-point concerns (1 being the most important, 5 being the least). Instinctively, I think that a separate project would be ideal for users, but maintainers want DRY.

**Comment by nicolas-leydet** [comment]
I think 1 is a non issue :
In the example domain directory, you would have one file per type (with each file name mentioning their type). It would actually be easier to reference in a tutorial/explanation. This separation in different type directories is actually unnecessary when you start a very simple project.

2 - Yes, I think you probably need "common" directories like "widgets" and "helpers" but I would have them either structure.

3/5 - You already explain the why and the how in the readme and FAQ. We just need a file explaining what's constitute a domain and what can constitute a widget / helper. You can obviously link to good article explaining the subject. 

4 - Angular example had a similar organisation at the beginning and went to a transition to domain-based

I think the biggest issue for a beginner is probably "what constitute a domain ? am I going to reuse this in the future ?". 
But, it is an issue for more experienced developers too. 
That's one of the reason why you should (or do) refactor all the time.

**Comment by coryhouse** [comment]
Closing since we've decided to stick with current structure, but certainly appreciate the suggestion and can see the merits!
