### ISSUE TITLE
Create Setup command

### ISSUE THREAD

**Issue by coryhouse** [coryhouse/react-slingshot#148]
This command can do the following:
1. Remove the git file (so a clone of this repo doesn't contain the git history)
2. Run npm install
3. Remove itself so it's not accidentally run again

**Comment by nlarche** [comment]
what did you think about changing package.json name properties and parent directory name  with ?

**Comment by coryhouse** [comment]
Changing the package.json name makes a lot of sense. People can already specify the name of the directory themselves when cloning, so not too worried about that.

**Comment by j5v** [comment]
1. Personally, I've been removing the repo link in `package.json`, just so I don't accidentally contaminate the project here.

   I think you can specify  `--depth=1` to avoid fetching the entire history of the project. Perhaps suggest the appropriate git command in your `README`?

2. I would not include `npm install` in a script. Developers would do that anyway (`npm i`), as habit.

   Generally: Do you see setup scripts in other projects?

**Comment by coryhouse** [comment]
@j5v Dedicated setup scripts are rare - traditionally such tasks would be handled by something like a Yeoman generator, but I've been trying to avoid going that route.

Regarding running npm install - I agree that people understand the need, just figured it might as well all be handled via one command.

**Comment by gargrave** [comment]
I am planning on taking a whack at this. A couple quick thoughts:

- Since we are deleting the original/cloned repo, is it safe to assume we can go ahead and let the setup script init a new repo?
- Regarding the discussion of `package.json`, there are quite a few fields in there that could potentially be reset for a fresh project: name, version, description, auth, license, repository, etc. Is it worth prompting the user in the setup script to enter new values here, or would you prefer to keep the script fully automated, and not require any user interaction? (Maybe if it's the latter, we could just add a message to the end to remind to user to update these manually or something...)

**Comment by coryhouse** [comment]
@gargrave Great! Good questions. 

I wouldn't worry about initializing a new repo since not everyone uses Git.

I think prompting for package.json would be really slick and helpful.

**Comment by gargrave** [comment]
Thanks, Cory. I should have a PR for you sometime in the very near future.

**Comment by coryhouse** [comment]
Closing since PR https://github.com/coryhouse/react-slingshot/pull/160 delivered this. Thanks @gargrave :+1:
