### ISSUE TITLE
Add carte-blanche

### ISSUE THREAD

**Issue by alejandronanez** [coryhouse/react-slingshot#158]
What about adding [Carte Blanche](https://github.com/carteb/carte-blanche) to this project?

**Comment by coryhouse** [comment]
There are many alternatives in this space, so I'm not sure I see the benefit of Slingshot integrating a particular one. And since Carte Blanche is about having an isolated environment, I don't see the benefit of integrating it with Slingshot. If one found it useful, they'd likely logically keep them separate.
