### ISSUE TITLE
Fatal error when running npm run build

### ISSUE THREAD

**Issue by rustanacexd** [coryhouse/react-slingshot#244]
Node version: v6.2.2

npm version: 3.9.5

Operating system: OS X 10.11.5

Command line used: iterm2 

Steps to reproduce:  npm run build

Screenshot : http://take.ms/Aarxn

**Comment by kwelch** [comment]
Are you having issues with any other commands?

**Comment by rustanacexd** [comment]
```npm run clean-dist``` and ```npm run test``` works fine and yeah you are right npm run lint does not. I have 5 errors ( mostly props validation) does it need to have zero errors before I can npm run build?

**Comment by kwelch** [comment]
Yes, the reason the lint rules are errors is so that they don't get built and sent to production is a state that could cause an error. So they are a dependent of the build process that both the linting and tests pass. 

The lint rules are easily configurable if they are not to your liking, just edit the `.eslintrc` file in the root of the project.

**Comment by rustanacexd** [comment]
got it. thanks a lot @kwelch
