### ISSUE TITLE
npm install error with querystring

### ISSUE THREAD

**Issue by cyprusglobe** [coryhouse/react-slingshot#252]
Node version: v6.2.2

npm version: v3.10.6

Operating system: OSX El Capitan

Command line used: ```npm install```

Steps to reproduce: run ```npm install```

error log shown bellow:
```
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/koder/.nvm/versions/node/v6.2.2/bin/node" "/Users/koder/.nvm/versions/node/v6.2.2/bin/npm" "install"
npm ERR! node v6.2.2
npm ERR! npm  v3.10.6

npm ERR! No compatible version found: querystring@1.2.0
npm ERR! Valid install targets:
npm ERR! 0.2.0, 0.1.0, 0.0.4, 0.0.1
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/koder/Code/nm-property-insurance/npm-debug.log
```

**Comment by kwelch** [comment]
Was `querystring` a package you added? It is not in `package.json` by default. This is not a direct dependency, so debugging this would be difficult. It looks like `querystring` is dependent somewhere in the chain with a version that is not published. 

Closing since `querystring` is not a direct dependency and the issue is not specific to react-slingshot.
