### ISSUE TITLE
Is there a way to easily update my package.json corresponding to the latest version in this repo and including my modules? I also noticed that when i install a new module its not in semantic version

### ISSUE THREAD

**Issue by seanyu4296** [coryhouse/react-slingshot#268]
Node version:

npm version:

Operating system:

Command line used:

Steps to reproduce:

**Comment by kwelch** [comment]
If all you are trying to do is have the same dependancies as Slingshot, you just need to copy those section from Slingshot `package.json` to your `package.json`. This is not a method I recommend since most dependency changes are due to equal changes in the code and the updates may not be necessary without the sibling code changes. 

As for the semantic version question, I am not sure I am clear on this one? Can you elaborate or post an example?

**Comment by seanyu4296** [comment]
@kwelch 

so for example i install superagent by typing

npm install superagent --save-dev

`"superagent": "2.1.0",`

it automatically ends up without a  "^" in its version, which i think from experience is the default right?
I'm fairly new to javascript, so i'm not quite sure.

**Comment by kwelch** [comment]
Ah, if you are seeing `"2.1.0"` in your `package.json` that is due to the [`.npmrc`](https://github.com/coryhouse/react-slingshot/blob/master/.npmrc) it is setup to save the exact version you install. 

There are a few reasons for this. 
- Prevents differences when running on CI vs local machine
- Not everyone does SemVer right (yet)

If you expected the `package.json` to save it as `"^2.1.0"` you can either the file: 
```diff
-save-exact=true
+save-prefix='^'
```

Or, you can delete this file and use the default, which is currently `'^'`, for hight control I recommend using the npm-config file.

**Comment by seanyu4296** [comment]
Ah, thank you very much for enlightening me!
