### ISSUE TITLE
PR: Add support for flowtype

### ISSUE THREAD

**Issue by amilajack** [coryhouse/react-slingshot#272]
Flow would be a great addition to this project. Would a PR for adding support for it be welcome?

**Comment by coryhouse** [comment]
I'm unclear what code changes would be required, but am open to reviewing a PR. Thanks for the offer!

**Comment by amilajack** [comment]
Some of the changes include adding `.flowconfig`, `babel-plugin-strip-flow-types`, and some initial type annotations.

**Comment by coryhouse** [comment]
Ah, gotcha. After thinking further, I don't think it makes sense to take an opinion on this. Some prefer plain Babel, some TS, some Flow, so think we'll keep this out for now. Thanks though!

**Comment by praxiq** [comment]
I'd like to second this feature request!

"Some prefer plain Babel, some TS, some Flow..."

I appreciate your concerns, but here are my thoughts on this:

- As you point out, lots of people don't know or care what Flow is, and don't want to bother with type annotations. That's fine - they can still benefit from it! Flow's type inference is pretty good, so it can catch lots of type errors in ordinary, un-annotated JS. For these users, flow is basically an extra level of linting. React-slingshot already includes ESLint to help people catch error early - Flow complements that perfectly.

- As for Flow vs TS: As far as I can see, Flow is a straightforward improvement on TS. Its powerful, flexible type system does everything TS does, just as elegantly (or more), and also does a bunch more stuff. Unless someone is already using TS and doesn't want to switch, there's no downside to Flow - but since react-slingshot is focused on people building new projects, that's not a big issue!

**Comment by amilajack** [comment]
Also standardization of static typing in JS largely depends on the success of flow and typescript. If those technologies do not receive widespread usage, it isnt likely that types will be standardized. I think at the least, support for flow should be supported out of the box and people can mess around with if they choose.
