### ISSUE TITLE
Update Redux DevTools Extension to support latest version

### ISSUE THREAD

**Issue by kwelch** [coryhouse/react-slingshot#299]
Redux DevTools extension is deprecating the method that slingshot is using to integrate. 

[Here is the example on setup similar to how we already.](https://github.com/zalmoxisus/redux-devtools-extension#12-advanced-store-setup)

~~Ideally, we should support both versions.~~

**Comment by zalmoxisus** [comment]
Hey @kwelch,

We just renamed `window.devToolsExtension` to `window.__REDUX_DEVTOOLS_EXTENSION__` as there were complains as it being to generic.

Also added a second method  `window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__` which is more suitable for your case. It makes the integration with other enhancers and middlewares better, specifically the ability to lock the app (anhancers and middlewares) when the `lock` button is pressed, and for remotely dispatched action creators to be passed via enhancers/middlewares. Also there's no need for the noop function (`f => f`).

I think supporting the deprecated global variable isn't necessary as Chrome extension is updated automatically. Only for Firefox is possible to disable the automatic updates, but [it's been more than a month since we made those changes](https://github.com/zalmoxisus/redux-devtools-extension/issues/220).

**Comment by kwelch** [comment]
@zalmoxisus, 

The upgrade was very simple, I just didn't have a chance to do it for slingshot yet. I agree, with autoupdates and it has been deployed for over a month it makes sense to not support both. 

The extension is extremely useful. Thanks for you work on it and your added details here.

**Comment by nickytonline** [comment]
@kwelch, PR is up for this.
