### ISSUE TITLE
Could you please provide simple tutorial how to create new page then use redux eg: login page

### ISSUE THREAD

**Issue by azulkipli** [coryhouse/react-slingshot#330]
Could you please provide simple tutorial how to create new page then use redux eg: login page.

Thanks

**Comment by coryhouse** [comment]
I walk through the process in detail in [this Pluralsight course](https://app.pluralsight.com/library/courses/react-redux-react-router-es6/table-of-contents).

There's no simple answer to this since some pages will require new actions and reducers, others will not, but the general steps are:
1. Create Action type constant
2. Create Action creator
3. Reducer
4. Add reducer to store
5. Connect component to redux store using redux-connect
6. Dispatch action to begin the unidirectional flow.
