### ISSUE TITLE
'open' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by ghost** [coryhouse/react-slingshot#350]
Node version: 6.9.2 (also tried 5.12.0)

npm version: 3.10.5

Operating system: Windows 10 (also tried Mint Linux 18.1)

Command line used: ConEmu, Native Windows Console, Powershell, and Native Linux console

Steps to reproduce: npm run open:cover

Coverage runs without issue (after applying the istanbul 0.4.4 fix) but am getting the following error message: 'open' is not recognized as an internal or external command,
operable program or batch file. when it tries to open the coverage/index.html file.

**Comment by coryhouse** [comment]
That's strange. Do you see open in your node_modules folder?

**Comment by whoisjonniegalt** [comment]
Cory, I do see open in the node_modules folder. Looking at the ReadMe say that Darwin (Mac OSX) uses 'open' and Win32 uses 'start'. I am going to dig into it more tomorrow.

Enjoyed the course on Pluralsight, using Slingshot for a friends portfolio and to teach him React.

**Comment by whoisjonniegalt** [comment]
Okay more information.

This is a problem with using NPM scripts rather than using GULP or any other Task Manager. Since the commands node_open uses are dependent on the OS being used, the package.json has to be changed to use 'start' on Windows rather than the 'open' one that is in the package.json. For Linux, it is another command also - this explains why it did not work for me in either environment.

https://github.com/pwnall/node-open/issues/55

So the work around being recommending it to create a node script that can be used to determine the OS and then issue the proper command. While NPM Scripts might be all the rage, they are not a complete substitution for a good old fashion task runner in which your can execute code.

Very similar to problems we've been finding with Electrode. Hate to say it but with NPM scripts there is too much of the ICOMM (It Compiles On My Machine) mentality. 

As a suggestion, perhaps it would be better to move some pieces to a gulpfile (or grunt - don't really care), this way issues like this can be mitigated. I'd be happy to try and take this on and issue a PR.

**Comment by coryhouse** [comment]
Thanks for digging into this! 👍 

We don't need Gulp/Grunt to fix this. This issue could have just as easily happened if a Grunt/Gulp plugin didn't provide proper Linux support. 

Calling a separate script that uses [open](https://www.npmjs.com/package/open) should do the trick, since it appears to provide full cross-platform support.

I'd welcome a PR that does so! :)

**Comment by whoisjonniegalt** [comment]
You're right - it could of easily happened with Grunt or Gulp as well. I noticed after the fact that you already have some node scripts being used, so my plan will be to create one for 'open:cover' that will just abstract out the proper open call.

I should be able to get to that today or tomorrow. Thanks again for a great starting point as well as the quick responses. I've enjoyed your React courses on Pluralsight, they became the catalyst for us bring React into our company. Happy New Year Cory!

**Comment by whoisjonniegalt** [comment]
@coryhouse I've got a fix in place, but unfortunately the project version I was helping a friend out with was cloned before the dev dependencies were updated last. Now when I do a fresh fork, run all the setup and start, followed by 

> npm run test:cover

the cover code fails. All boiling down to isparta and istanbul again. I'd like to suggest moving to instanbul and nyc instead. I'd also be more than willing to take that on as well. The 'open' fix was super simple, so not really worried about that aspect. Just kind of a bummer everything else is working nicely, but isparta is being a PITA. Also noticed it is no longer being maintained, so probably best to investigate moving away from it. Does this have any crossover with the Jest migration?

**Comment by coryhouse** [comment]
Ah, sorry about that. Yes, you're right. I'm good with the move to NYC for now. 

Yes, moving to Jest would also replace the need for istanbul but the Jest move is on hold until we can find a way to make Jest output minimally like Mocha does, so this move makes sense for now. 

Thanks so much! 👍

**Comment by whoisjonniegalt** [comment]
Sounds good, I'll start on this tomorrow. I want to play with NYC first to make sure I understand it. So far looks pretty straight forward.

**Comment by kwelch** [comment]
Closing. PR #245 addressed some of the test:cover issues. Further discussion on test coverage will take place in either #223(Test Coverage) or the #262 (Jest Migration).

**Comment by SaumoRoy** [comment]
Perfectly works on start or Start in Windows operating system.

**Comment by francis-vila** [comment]
I'm on Windows 10, in a project freshly created with expo's `create-expo-app` utility. I'm trying to use debugging.

I read in https://docs.expo.dev/workflow/debugging/ 

> Open the project in Android Studio: `open -a /Applications/Android\ Studio.app ./android` 


I typed the command and get the message:
 ` 'open' is not recognized as an internal or external command, operable program or batch file.`

I tried replacing open with start:
`start -a /Applications/Android\ Studio.app ./android`

I got the response:
` The system cannot find the file -a.`

I removed the -a, got the answer: 
`Invalid switch - "/Applications".`
