### ISSUE TITLE
Initial run failing

### ISSUE THREAD

**Issue by dewaldgaljaard** [coryhouse/react-slingshot#364]
Node version: 6.9.2

npm version: 3.10.9

Operating system: Sierra

Command line used: npm start

Steps to reproduce: 
1) Download latest build
2) npm install
3) npm start

Result: Failed at the react-slingshot@5.0.0 prestart script 'npm-run-all --parallel start-message'.

Seems related to: https://github.com/coryhouse/react-slingshot/issues/231

**Comment by kwelch** [comment]
Can you explain how you downloaded the repo?

I was unable to reproduce this. Steps I took. 
1. Open term to react-slingshot working directory
2. Pulled latest `master`
3. Ran `git clean -fdx` - this removes all files/directories not commited or in `.gitignore` this ensures I don't have any `node_modules` not specified in the package.json
4. Ran `npm install` - per-instructions
5. Ran `npm start` - per-instructions

I was able to open see the example app. 

Could you please clone the latest and see if the issue persists? Version 6.0.0 was released since this was opened and includes new features such as Webpack 2, Jest, and PostCSS w/ autoprefixer. There may have been changing with the last few days that may resolve the error you were receiving.

**Comment by dewaldgaljaard** [comment]
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: watch null EMFILE
    at exports._errnoException (util.js:907:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1217:21)

npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test" "--" "--watch"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! react-slingshot@5.0.0 test: `jest "--watch"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-slingshot@5.0.0 test script 'jest "--watch"'.
npm ERR! This is most likely a problem with the react-slingshot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     jest "--watch"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-slingshot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls react-slingshot
npm ERR! There is likely additional logging output above.

**Comment by dewaldgaljaard** [comment]
Up and running now. Thanks.
