### ISSUE TITLE
node: bad option: --harmony_proxies

### ISSUE THREAD

**Issue by arshdkhn1** [coryhouse/react-slingshot#366]
Node version: v7.5.0

npm version: 4.1.2

Operating system: Elementary OS Luna

Command line used: Hyper / 

Steps to reproduce: `npm start -s`

Hi, I get `node: bad option: --harmony_proxies` as error when I try to start the app. When I downgraded my node to lts 6.9.5 then the error was gone.

Creating this issue to bring it to your attention if it hasn't yet.

**Comment by XOP** [comment]
Same for me with `7.2.0`

**Comment by dotnetnorm** [comment]
Remove it from test wit 7.2.0 it is not needed.  It is on the test mpmaria@us.ibm.com script.

**Comment by n-makarov** [comment]
Node 7 has removed the `harmony_proxies` flag in favor of `harmony`. You need to update `test`  command in the `package.json` file by replacing `--harmony_proxies` with `--harmony`.

**Comment by kwelch** [comment]
This flag is not necessary for v6 of node either, but was replaced with a no-op. It was deprecated in 7 as @n-makarov stated. 

Due to slingshot supporting Node v4 and v5, this is a necessary flag.

I do understand the pain point, if someone would like to update docs around this that a PR would be greatly appreciated.

**Comment by coryhouse** [comment]
I believe I've resolved the issue for local dev via #368. 

Still looking for a fix for CI build on Node 7. Open to ideas.

**Comment by nickytonline** [comment]
@coryhouse, just typing out loud here ;). We could have a script that detects which version of node is running via `const requiresHarmonyFlag = parseInt(/^v(\d+)\./.exec(process.version)[1], 10) >= 7` and if it's true, we run `node node_modules/jest/bin/jest`, otherwise we run `node --harmony_proxies node_modules/jest/bin/jest`.

**Comment by coryhouse** [comment]
Yeah, that'd do it. But man, it'd be ugly and confusing to put all that in an npm script. Would be more acceptable abstracted into a js file...

**Comment by nickytonline** [comment]
@coryhouse, yeah, I meant in a JS file. Forgot to finish typing my thoughts ;)

**Comment by nickytonline** [comment]
I'll throw up a PR for this this weekend.

**Comment by nickytonline** [comment]
I thought I'd get to this this weekend but did not. I'll try and knock this off this week.

**Comment by coryhouse** [comment]
Excellent 🎉  - Eager to turn 7 back on for CI. :)

**Comment by coryhouse** [comment]
Resolved by @nickytonline in #378. 🎉
