### ISSUE TITLE
How fix import compass ?

### ISSUE THREAD

**Issue by VectorM** [coryhouse/react-slingshot#396]
Node version:6.10.0

npm version:3.10.10

Operating system:Win64

Command line used:custom terminal

Steps to reproduce:

```
ERROR in ./~/css-loader?sourceMap!./~/postcss-loader!./~/sass-loader/lib/loader.js?sourceMap!./src/scss/screen.scss
Module build failed:
@import "compass/css3/images";
^
      File to import not found or unreadable: compass/css3/images.


```

How fix it?

**Comment by kwelch** [comment]
This looks to be a dependency issue, webpack is unable to find the `compass` package. This could be because either the package is not installed or this a a file and the path is not fully qualified. 

Unless you made some changes to webpack, then there are some more advanced areas this could be failing.

**Comment by coryhouse** [comment]
Compass isn't part of Slingshot, so I assume you've added compass to your project, correct?

**Comment by nickytonline** [comment]
@VectorM, I'm closing this issue as Compass is not a part of react-slingshot as @coryhouse mentioned.  As @kwelch pointed out this appears to be an import issue in your SASS file reated to Compass.
