### ISSUE TITLE
TDD / BDD based setup in the slingshot ?

### ISSUE THREAD

**Issue by Technologeek** [coryhouse/react-slingshot#419]
Not sure if the issue has been raised before but I'd like to know if the slingshot can be improved to integrate any TDD/BDD based development tools like Mocha /Chai  ? I can still somehow manage to get the set-up run manually but would be nicer if this boiler plate came inbuilt with an option to integrate them.

Thank you!

**Comment by RoM4iK** [comment]
I think Jest is good enough to write both TDD and BDD tests.

**Comment by coryhouse** [comment]
Agreed with @RoM4iK. What feature is missing from Jest that you enjoy with Mocha?

**Comment by Technologeek** [comment]
Thanks for your response.Initially,I thought Jest was the correct choice for React apps but after reading [this reddit](https://www.reddit.com/r/reactjs/comments/3557vh/mocha_or_jest/) post,seems like developers are more conformable with using mocha.

**Comment by coryhouse** [comment]
That post is from a year ago. Facebook gave Jest a full-time team about that time and it has radically improved since then. My question about what you can do in Mocha/Jasmine that Jest can't do stands. 

I'll say this: Jest has snapshot testing, which neither Jasmine nor Mocha support. It also has mocking and assertions built-in, unlike Mocha.

**Comment by kwelch** [comment]
I asked a question about why jest during the migration. Not sure how much help it will be but here is a link to the comment. 

https://github.com/coryhouse/react-slingshot/issues/262#issuecomment-252485511
