### ISSUE TITLE
mild babel-polyfill confusion

### ISSUE THREAD

**Issue by conoverm** [coryhouse/react-slingshot#433]
babel-polyfill is listed in `devDependencies` in react-slingshot. On the babel-polyfill docs pages it states: 

> Because this is a polyfill (which will run before your source code), we need it to be a dependency, not a devDependency

[babel-polyfill](https://babeljs.io/docs/usage/polyfill/)

I moved babel-polyfill to dependencies and included it in the `entry` array in both `webpack.config` files. Is there a reason react-slingshot has it in devDependencies? (Have I broken something in react-slingshot and don't realize it?)

**Comment by kwelch** [comment]
I believe it is a `devDependency` since it is not needed at runtime. It is not imported in a  file but it is used only in the build and deploy process. 

In my opinion since it is a web app there is not much need for either. Dev deps are more necessary with libraries that are installed.

**Comment by coryhouse** [comment]
Yes, babel-polyfill is potentially useful for production as well if you want to use features that require the polyfill on your production app. I chose not to include it in the prod build by default since it's quite heavy (~50k). You're typically better off pulling in the specific polyfills you need for production.
