### ISSUE TITLE
Drop browsersync completely in production build

### ISSUE THREAD

**Issue by eldyvoon** [coryhouse/react-slingshot#477]
Why in `npm run build` we still use browsersync? browsersync make sense for development. I deployed my app by running npm run build, expect everything to worked, but I saw movement on my app without me clicking anything, then I realised it was caused by browsersync. 

What's the purpose of browsersync in production and how to turn it off? just comment the config in `tools/disServer.js` ?

**Comment by coryhouse** [comment]
Slingshot generates static files to the dist folder. Browsersync is just set up so that you can run the production build on your local machine for review. For production, you should use a traditional web server to serve the static files written to /dist. So your deployment process really just needs to copy the files in /dist to your prod webserver.

**Comment by eldyvoon** [comment]
traditional server means? I usually use ubuntu and nginx for SAP with node.

**Comment by eldyvoon** [comment]
Tried to get ampp for a quick test, I place files in dist folder and run index.html, I got this error

https://i.imgur.com/iqZ6T7e.png

any clue?

**Comment by coryhouse** [comment]
Serve the app from web root instead of a subfolder and it'll work

**Comment by eldyvoon** [comment]
localhost/react is the web root, I create a react folder to hold those files.

**Comment by eldyvoon** [comment]
oh ya placing it in a folder won't work, have to put those file in the root. Got it, thanks for the help Cory!

**Comment by eldyvoon** [comment]
But I still curios, is there anyway I can turn off browsersync?

**Comment by kwelch** [comment]
Here are some recommendations on how to remove browsersync  - https://github.com/coryhouse/react-slingshot/issues/477

**Comment by eldyvoon** [comment]
@kwelch Couldn't click the link, typo?

**Comment by kwelch** [comment]
Not sure it works on my end. You can also look up react-slingshot issue #477

**Comment by nickytonline** [comment]
Works on my end too.

**Comment by eldyvoon** [comment]
@kwelch @nickytonline the link redirect me to the same page, https://drive.google.com/file/d/0B89f1Cq6M9EQcnNkc1ZGclVManc/view

**Comment by nickytonline** [comment]
The link is for #477, which is `https://github.com/coryhouse/react-slingshot/issues/477`

**Comment by eldyvoon** [comment]
@nickytonline I'm seeing my own issue https://i.imgur.com/YHbsVFP.png

**Comment by nickytonline** [comment]
@kwelch, we are silly. I think you meant to say issue https://github.com/coryhouse/react-slingshot/issues/474 ?

**Comment by eldyvoon** [comment]
@mikedevita Thanks for sharing, do you do any automation in step 4? It's tedious to copy manually to server.

**Comment by mikedevita** [comment]
unfortunately no I don't. not even aware if there is an automated process for that part. typically we use http-proxy-middleware and reverse proxy to the sap back end during development. that way we only push to sap when were ready for a release and we know the UI is good to go.

I'm at SAP TechEd right now but shoot me an email Mike.devita@srpnet.com<mailto:Mike.devita@srpnet.com> if you need further help since this is out of this kits scope and I'd hate to clutter the issue up with SAP stuff 😜.
