### ISSUE TITLE
Switching from SASS to CSS in JS

### ISSUE THREAD

**Issue by eferrervaughn** [coryhouse/react-slingshot#505]
Hello,

First React-Slingshot is an amazing boilerplate, and its been a huge help w/ me starting out in React. I was wondering about using a Inline CSS library instead of SASS (Emotion or Styled-Components). Just want to check if my thinking is correct.

1. Yarn Add React-Emotion
2. Yarn Remove node-sass & sass loader
3. Add some code to webpack build to support Emotion??
4. Remove sass support from the Webpack config??

3 & 4 are new to me, so I want to be sure I am not breaking anything.

**Comment by kwelch** [comment]
All you should have to do is Step 1. Step 2 is start using it. Step 3 - profit?

On a more serious note, your approach for the other steps are accurate, with one exception. To my knowledge there is no work that needs to be done in webpack to support css-in-js. Removing the sass items is not necessary but good clean up. 

One of my favorite things about react-slingshot, is the simplicity of it. We use to have comments on every line of the webpack files which was how I learned to navigate and configure webpack. 

If you are planning on moving forward with css-in-js to the extent of not using any css at all you would need to follow these steps. _*(NOTE: this is not necessary, but if you wish to do this webpack will no longer understand css files)*_
- Remove [these lines in `webpack.config.dev.js`](https://github.com/coryhouse/react-slingshot/blob/master/webpack.config.dev.js#L97-L123)
- Remove the following lines from `webpack.config.prod.js`
  - Line 4 => This is a plugin that creates external css files based on loaded css
  - Line 33 & 34 => Activates the plugin mention above
  - Lines 129-157 => configures webpack on how to handle and process css & sass files

**Comment by eferrervaughn** [comment]
Dude this was so helpful!!! Think this is my last thing to do and now I can start building. Thanks for the response!

**Comment by nlindroos** [comment]
Hi @eferrervaughn, did you manage to get Emotion working? Normal usage seems to work out of the box by just installing the correct dependencies. The [element shorthand functionality](https://emotion.sh/docs/styled#element-shorthand) however will compile, but the required [babel plugin, `babel-plugin-emotion`](https://emotion.sh/docs/babel-plugin-emotion), does not seem to work properly and results in an uncaught error "You're trying to use the styled shorthand without babel-plugin-emotion." in the browser.

I've tried using both the simplest Babel config `"plugins": ["emotion"]` and separate configs for dev and prod using Babel's env property, as described in the [documentation](https://emotion.sh/docs/babel-plugin-emotion#via-babelrc-recommended). Are any modifications to e.g. webpack configs needed in order to support additional Babel plugins @kwelch?

**Comment by kwelch** [comment]
@nlindroos 

Our babel config is in the `package.json` and is setup on a per env state. You may want to review that and ensure you have added it to all of the envs. 
https://github.com/coryhouse/react-slingshot/blob/master/package.json#L130-L171

I would not expect to see any need to change the webpack config since we have the babel-loader in place. Unless there is any necessary changes for emotion to work. I have not used it so I am not sure.
