### ISSUE TITLE
Sass calc() doesn't work properly in this kit

### ISSUE THREAD

**Issue by leonimurilo** [coryhouse/react-slingshot#526]
I have the following sass code for a grid column:
Working fine in Codepen: https://codepen.io/anon/pen/zpwpOm?editors=1100
```sass
// 1rem = 10px
$grid-width: 114rem
$gutter-horizontal: 6rem
.row
  max-width: $grid-width
  .col-1-of-2
    width: calc((100% - #{$gutter-horizontal}) / 2)
```

```jsx
<div className="row">
  <div className="col-1-of-2">Col 1 of 2</div>
  <div className="col-1-of-2">Col 1 of 2</div>
</div>
```

Since the grid width is 1140px (max size triggered) and $gutter-horizonta is 60px, each column width should be 540px so I would have 540px + 60px + 540px = 1140px. However for some reason the column width that appears when I inspect the element in any browser is 47% which is no sense since 47% is 535.8px not 540px.

Why is the following code being converted to no sense percentages?
`    width: calc((100% - #{$gutter-horizontal}) / 2)`

It should be converted to 540px not 47%
![screen shot 2017-12-30 at 10 46 31](https://user-images.githubusercontent.com/14261943/34454352-c4d01c86-ed50-11e7-91b3-4b410c50ca02.png)

Of course I end with a unexpected spacement aftet the second column:

![screen shot 2017-12-30 at 10 07 22](https://user-images.githubusercontent.com/14261943/34454351-c4ae222a-ed50-11e7-834f-e28cf88de23c.png)

For some reason the width in the compiled css is 47% while in any other place I test this code, like in a separate node-sass project or in Codepen it works perfectly.

node-sass: 4.7.2
sass-loader: 6.0.6

Node version:
6.2.2 (also tried 8.9)
npm version:
3.9.5
Operating system:
macOS High Sierra
Command line used:
npm start

**Comment by nickytonline** [comment]
@leonimurilo,

If everything builds and the SASS is compiled to CSS, I don't see how there is a problem with React Slingshot and I find it highly unlikely that there is an issue with node-sass or sass-loader.

Do you have a public repo to compare your SASS with that of the Code Pen to further investigate the issue? Thanks.

**Comment by leonimurilo** [comment]
@nickytonline,

Yes I do: https://github.com/leonimurilo/Natours-React
I am using the 7-1 sass pattern and the code that I showed in codepen is distributed in:

### sass files
./src/styles/abstracts/_variables.sass
./src/styles/abstracts/_mixins.sass
./src/styles/abstracts/_grid.sass (where the calcs are made)

### React components
./src/components/LandingPage/index.js (where I could put the grid)
./src/components/GridExample/index.js (A sample component using the grid classes)

I spent hours trying to find out why the css file is being compiled with the percentage values intead of the calc() values.

Since I'm following an Udemy course, here it is the instructor code:
https://github.com/jonasschmedtmann/advanced-css-course/tree/master/Natours/after-S05

Note that he has the same calc() as I do and if you go to ./after-S05/css/style.css (file that was compiled base on the sass files) you will see that the grid column classes have the correct calc() definitions while my css file that was generated by this starter kit, doesn't :(

**Comment by nickytonline** [comment]
They're appears to be no `_grid.sass` file in the https://github.com/leonimurilo/Natours-React/tree/master/src/styles/abstracts folder of your repository. Has everything local been pushed to your master branch?

**Comment by leonimurilo** [comment]
Oh sorry. Copy and paste mistake. 
It is in /src/styles/layout/_grid.sass

**Comment by nickytonline** [comment]
👍

**Comment by jhnns** [comment]
You're applying [the less-loader *and* the sass-loader](https://github.com/coryhouse/react-slingshot/blob/9a8a8483f3b0ad0c9b02c2de752d0ed4943b65c4/webpack.config.prod.js#L147-L159) on the same file. This change has been introduced recently with https://github.com/coryhouse/react-slingshot/pull/512. Maybe this problem is based on a misunderstanding of the `includePaths` option. It will be passed as option to the respective loader. It does not constrain the folders where the loader will be executed. You need to create two separate loader chains with [two separate extract-text-plugin instances as shown in the readme](https://github.com/webpack-contrib/extract-text-webpack-plugin#multiple-instances).

Also note that the Less doesn't have an `includePaths` option. The option is called `paths`.

---

@leonimurilo 

> The only differences I found is the he's using scss instead of sass and I tried to put all the course stuff in a React project.

The react-slingshot setup is totally different than your instructor's setup. There is a lot of going on with your CSS. If you're just learning this stuff, I would recommend to start with a bare repository and stick to the instructions :)

**Comment by nickytonline** [comment]
Thanks for chiming in @jhnns! Always nice when someone from the webpack team lends a hand. 👍 🔥. I'll open an issue to fix the webpack prod config to fix the Less loader and go with your recommendation of separate loader chains.

**Comment by leonimurilo** [comment]
@nickytonline

The problem also happens with the dev configs, right? Because I am running the project in a dev env.

I also haven't understand the purpose of the extract-text-plugin. 

(I am new into this things so sorry if I do stupid questions)

**Comment by nickytonline** [comment]
@leonimurilo, the purpose of the extract-text-plugin is to generate a CSS file from all the pre-processor files in your project (SASS, LESS or both).

I think @jhnns is right. Let's keep it simple to begin with. I don't think there's an issue with the dev configuration, so let's go back to basics first.

* Your Code Pen works from what I saw and from what you told me the expected output was supposed to be.
* In the course on Udemy, do you have it working?
* Instead of the 7-1 pattern, for now, grab all that SASS you wrote in those files in your clone/fork of react-slingshot and paste it in to one SASS file in a clone of your Code Pen. Does it render as you would expect?

Let me know and we'll go from there.

**Comment by leonimurilo** [comment]
@nickytonline I have already tested the code that is in codepen in the react-slingshot and everything works fine except the ccs3 calc() functions. 

In any other place except react-slingshot, when I inspect the element using the browser dev tools, the calc() function in the selector is like the following:

`width: calc((100% - 2 * 6rem) / 3);`

Which is exactly what I wrote in my sass file.

However, if I inspect the same element and check its css selectors the, calc functions are defined just like this:

`width: calc(29%);`

Which doesn't make any sense. As jhnns said, the Less loader are being applied in the same file and that is why it is turning the `width: calc((100% - 2 * 6rem) / 3);` into `width: calc(29%);` even though the calc() functions are in .sass/.scss files instead of .less files.

After some research I found that if the following option is disabled by default in Less and it is the most reasonable explanation for my problem:

http://lesscss.org/usage/#command-line-usage-strict-math

Besides all this, I may be wrong, but I don't think the Less should be applied to the same "stuff" that sass have already been applied.

What do you think?

**Comment by coryhouse** [comment]
#512 regressed Sass support. 

Two options:
1. Remove Less support it since in retrospect I don't think it makes sense to support both.
2. Separate the Less loader config from the Sass Loader config in webpack.config so .less files aren't touched by the Sass loader and vice versa. 

I'd welcome a PR on either.

**Comment by leonimurilo** [comment]
I tried the second option in my project, but thanks to my low knowledge of webpack I did not succeed. Nonetheless I was able to remove Less stuff. 

I will do a pull request and you can decide if this is the best approach or not and, of course, if my changes are correct.

**Comment by nickytonline** [comment]
@coryhouse, I think removing the LESS support makes more sense. From there, we could just add to the documentation how to replace the SASS config with that of the LESS config.

**Comment by nickytonline** [comment]
@leonimurilo, with #526, do things calculate properly now in your CSS generated from SASS?

**Comment by leonimurilo** [comment]
@nickytonline yes It does. I've tested in my own project.

**Comment by nickytonline** [comment]
Great to hear.

**Comment by Yuliia1104** [comment]
HI Everyone,

I am following the same course with @leonimurilo but faced a bit different problem. I really hope you can advise  me something))
![Screen Shot 2021-09-08 at 9 24 12 PM](https://user-images.githubusercontent.com/82834309/132733574-18fe0c9f-44d7-4386-8902-38e95663f033.png)
 
Here is my codepen https://codepen.io/juli-soloviova/pen/GREWOGL?editors=1100

**Comment by coryhouse** [comment]
@Yuliia1104 - Can you share a link to the course you're referring to?

**Comment by Yuliia1104** [comment]
https://www.udemy.com/course/advanced-css-and-sass/learn/lecture/8274498?start=0#questions
sorry for such a long time response. I already solved the problem. I made a
mistake in naming classes.

чт, 9 сент. 2021 г. в 20:45, Cory House ***@***.***>:
