### ISSUE TITLE
Best practice for assets directory

### ISSUE THREAD

**Issue by syrys** [coryhouse/react-slingshot#550]
Hey All,

Looking for what the best practice for having a assets directory that you can call using strings. For example, lets say you want to attach some custom fonts, icons or images from your css, or dynamically select bunch of images from javascript strings (lets say depending on day, month, year, country etc, so you cant just import all of them).

These assets needs to be available for the `npm start`'s local dev server, how would i go about doing this? can use the `copy-webpack-plugin` or something to copy the directory over for the `npm run build` process i guess.

**Comment by syrys** [comment]
Also, is there anything wrong with the following line's image usage?:
`<div style={{width: 500, height: 500, backgroundColor: 'red', backgroundImage: 'url(/public/img/1.jpg)'}}></div>`
I added `/src/public/img/1.jpg`. The image is visible on `npm start`, but no image on `npm run build`. This is pretty worrying since the prod output is different to the dev output (even though it might be a dev issue).

**Comment by kwelch** [comment]
Personally I prefer to use to the images via a [require statement as our explains](https://github.com/coryhouse/react-slingshot/blob/master/docs/FAQ.md#how-do-i-handle-images). 

That being said I don't see the `copy-webpack-plugin` as a bad option. 

I prefer the require statement because this will ensure the files copied are only the ones used. In some cases such as dynamic file names that is not the case.

**Comment by nickytonline** [comment]
I'm going to close this as it's not really a react-slingshot issue but feel free to continue the discussion.
