### ISSUE TITLE
Involving Database

### ISSUE THREAD

**Issue by RefiPeretz** [coryhouse/react-slingshot#640]
Hey it was great if you could involve database in this example.
I'm following your course on Pluralsight and it's not clear to me where I should put database update If I would like to persist my store.

At first I thought it should be in the reducers but you said we should keep it pure and use only for states updates.
I'm a newbie in react.

**Comment by coryhouse** [comment]
A database would traditionally be handled on the server, and accessed via HTTP calls to an API that's hosted on the server and calls the DB. You can store data on the client via localStorage, but you probably want a real database. Since a database is a server-side concern, it's deliberately left out of Slingshot.

**Comment by RefiPeretz** [comment]
K make sense.
So this a pure question if you may. Where an API call for DB updating should be located in the Redux model. Should I just make in the component? how are we involving the state? I saw some examples off any connection with a backend, where the sate only manage call status.

I would like to hear you opinion on what is the best practice.

Anyway amazing course cheers.

**Comment by coryhouse** [comment]
API calls are traditionally made from your actions, using Redux-thunk or an alternative middleware.

**Comment by coryhouse** [comment]
And thanks for the kind feedback!
