### ISSUE TITLE
Hot reloading doesn't work with functional components

### ISSUE THREAD

**Issue by firstdoit** [coryhouse/react-slingshot#80]
Just thought I'd share this here since it took me 2 hours to find out why the functional components weren't hot reloading: https://github.com/gaearon/babel-plugin-react-transform/issues/57

**Comment by coryhouse** [comment]
Good point. It's a known limitation that will likely be resolved soon. Until then, those who care about hot reloading can avoid functional components.

**Comment by firstdoit** [comment]
Yep, might be good adding a comment on the functional components.

**Comment by coryhouse** [comment]
Added a [note to the FAQ](https://github.com/coryhouse/react-slingshot/blob/master/docs/FAQ.md#hot-reloading-isnt-working).

Thanks for pointing this out @firstdoit 

Closing since this isn't a Slingshot specific issue.

**Comment by gaearon** [comment]
React Hot Loader 3 supports functional components without destroying the state.
It supersedes both React Hot Loader and React Transform, and is built on lessons learned from both.
Check it out: https://github.com/gaearon/react-hot-boilerplate/pull/61

**Comment by coryhouse** [comment]
@gaearon - Nice! I'm just about to publish my React and Redux Pluralsight course. I used react-transform-hmre and warned people a change was coming. Any guess when 3.0 will release? Trying to decide if I should wait a few days so the course can use it.

**Comment by gaearon** [comment]
I will keep an eye on 3.0 alpha issues if any are reported and plan to fix them promptly. The documentation is the biggest blocker (https://github.com/gaearon/react-hot-loader/issues/243) because I’m unlikely to have time to work on it until in a month or so. So unless somebody contributes it, I’d say 3.0 can get out as late as June, just because of all the work unrelated to the code that needs to happen.

**Comment by coryhouse** [comment]
@gaearon Excellent - Thanks for the details and the quick reply!
