### ISSUE TITLE
npm install freezes at node-sass and can't run npm start

### ISSUE THREAD

**Issue by ripitrust** [coryhouse/react-slingshot#98]
When I run npm install, the installation process somehow freezes at 

`node-sass@3.4.2 install /Users/yangfan/Development/Javascript/react-slingshot/node_modules/node-sass`
`node scripts/install.js`

And I have to ctrl+c to terminate the process

After that if I try to run npm start, it will give me this error:

> /usr/local/lib/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126
     if (!option) this.log.error("Unknown option: " + alias + "." + key, ReferenceError);
                                ^

> TypeError: Cannot read property 'error' of undefined 

(the caret above is point to  this.log)

Not sure if this is my setting issue.

I am running on Mac OS X

**Comment by ripitrust** [comment]
This issue is gone after remove the whole directory and clone it again

**Comment by coryhouse** [comment]
Yes, this sort of issue can occur if you install new packages without removing references to old (potentially conflicting) packages. For instance, this can happen when you do this:

1. `git pull`
2. `npm install`

Why? Because there might have been a conflicting version of some package in node_modules. Your solution of wiping out node_modules works. An alternative that often works: `npm prune`.
