### ISSUE TITLE
How to use in production - NodeJS

### ISSUE THREAD

**Issue by kwelch** [coryhouse/react-slingshot#99]
This may be an overall question and  not slingshot specific, but how would one run this in production with a node server? 

It is simple enough to run within IIS with the `dist` as a directory, but it seems like trying to run/deploy as node js server it would need to have a second package.json to and scripts for the server side.

**Comment by coryhouse** [comment]
The resulting app written to /dist is just static files, so any host will do. No server-side needed. That's a feature.

If you want to host it via Node, then an extremely simple express setup would do the trick. [Here's an example](https://github.com/coryhouse/ps-redux/blob/master/tools/distServer.js).

**Comment by brianshrader7** [comment]
Question about this.... Shouldn't I be able to view the static HTML file in my browser?  When I use `npm run build` and pull up dist/index.html, I get a blank white screen with the following error:

`Failed to load resource: net::ERR_FILE_NOT_FOUND  file:///bundle.js `

Am I doing something wrong?  I'm up-to-date with master, so I should have the correct code.  I can get your TOH example to work, but not this one.

Node version: v5.0.0
NPM version: 3.8.6

**Comment by coryhouse** [comment]
`npm run build` should open your browser at the proper URL.

**Comment by brianshrader7** [comment]
Sorry, I should have been more clear.  It does open up the proper URL when I run `npm run build`, but my concern is getting my app onto my server.  

This is what I get when I try to put /dist onto my server without altering anything:
http://www.shradersworld.com/react-test/dist/

`Failed to load resource: the server responded with a status of 404 (Not Found) http://www.shradersworld.com/bundle.js`

Now the obvious solution is to change path in the generated HTML to just "bundle.js" instead of "/bundle.js".  Here's what I get when I do that:
http://www.shradersworld.com/react-test/dist2/

On the other hand, when I put your TOH example on my server, it loads perfectly: 
http://www.shradersworld.com/react-test/toh/

Am I missing something?  I assumed that I could just take /dist, throw it on my server, and it would work (as long as I wasn't doing any server-side stuff, which I'm not).

**Comment by coryhouse** [comment]
Place the contents of /dist in webroot on your server so that you can pull up the app at /.

**Comment by brianshrader7** [comment]
That worked!  Thanks a bunch.

While it worked with Slingshot, it didn't work with my actual app (which is based off of Slingshot):  http://shradersworld.com/index.html  

But at least i have a good starting point now.  My guess is some required JS files aren't being added correctly.

I truly appreciate both you writing the Slingshot code and you being so active on here even though it's not the true purpose of the issue-tracking system.  Thanks a bunch.

**Comment by coryhouse** [comment]
Great to hear! :)
